# Discord 配置
discord:
  # Discord 机器人令牌（在 config.local.yaml 中配置）
  token: ""
  # 通知消息发送的频道 ID（在 config.local.yaml 中配置）
  channel_id: 0
  # Discord 服务器 ID（在 config.local.yaml 中配置）
  guild_id: 0
  # 机器人命令前缀
  guild_id: 316418272469843969

# 监控配置
monitor:
  # 检查间隔时间（秒）
  check_interval: 10
  # 请求间隔时间（秒）
  request_delay: 2
  # 允许监控的域名列表
  allowed_domains:
    - "popmart.com"
    - "pop-mart.com"
    - "www.popmart.com"
    - "www.pop-mart.com"
    - "us.popmart.com"
    - "au.popmart.com"
    - "uk.popmart.com"
    - "sg.popmart.com"
    - "my.popmart.com"
    - "th.popmart.com"
    - "kr.popmart.com"
    - "jp.popmart.com"

# 存储配置
storage:
  # 监控商品数据存储文件路径
  data_file: "monitored_items.json"

# 日志配置
logging:
  # 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # 日志文件路径
  file: "logs/bot.log"
  # 是否在控制台输出日志
  console: true
  # 日志格式
  format: "%(asctime)s - %(levelname)s - %(message)s"
  # 日志文件最大大小（字节）
  max_size: 10485760  # 10MB
  # 保留的日志文件数量
  backup_count: 5
  # 第三方库日志级别
  third_party_levels:
    discord: "WARNING"
    selenium: "WARNING"
    urllib3: "WARNING"
    asyncio: "WARNING" 