# Discord 配置
discord:
  # Discord 机器人令牌（请替换为您的令牌）
  token: ""
  # 通知消息发送的频道 ID（请替换为您的频道ID）
  channel_id: 0
  # 服务器 ID（请替换为您的服务器ID，如果要全局注册命令则留空）
  guild_id: 0

# 监控配置
monitor:
  # 检查间隔时间（秒）
  check_interval: 1
  # 请求间隔时间（秒）
  request_delay: 1
  # 允许监控的域名列表
  allowed_domains:
    - "popmart.com"
    - "pop-mart.com"

# 存储配置
storage:
  # 监控商品数据存储文件路径
  data_file: "data/monitored_items.json"

# 日志配置
logging:
  # 日志级别 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  # 日志文件路径
  file: "logs/bot.log"
  # 是否在控制台输出日志
  console: true 