services:
  mysql:
    image: mysql:8.0
    container_name: popmart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-popmart123}
      MYSQL_DATABASE: ${DB_NAME:-popmart_watch}
      MYSQL_USER: ${DB_USERNAME:-popmart}
      MYSQL_PASSWORD: ${DB_PASSWORD:-popmart123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  pop-mart-watch:
    build: .
    container_name: popmart-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-popmart_watch}
      - DB_USERNAME=${DB_USERNAME:-popmart}
      - DB_PASSWORD=${DB_PASSWORD:-popmart123}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - ./logs:/app/logs
      - /dev/shm:/dev/shm  # Shared memory for Chrome
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mysql_data:
    driver: local 