# Pop Mart Watch Docker 环境配置
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${DB_NAME:popmart_watch}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8mb4
    username: ${DB_USERNAME:popmart}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false

# MyBatis Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath*:mapper/**/*.xml

# Pop Mart 监控配置
popmart:
  monitor:
    poll-interval: ${POPMART_MONITOR_POLL_INTERVAL:5}
    notification:
      type: ${POPMART_MONITOR_NOTIFICATION_TYPE:discord}
      discord:
        webhook-url: ${DISCORD_WEBHOOK_URL}
  
  discord:
    bot-token: ${DISCORD_BOT_TOKEN}
    guild-id: ${DISCORD_GUILD_ID}

# 日志配置
logging:
  level:
    com.popmart: INFO
    org.springframework.web: INFO
    org.mybatis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/pop-mart-watch.log
    max-size: 100MB
    max-history: 30

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: / 